### ISSUE TITLE
Functional requirements for Bubbl EVoting System version 1

### ISSUE THREAD

**Issue by LeanKhan** [bubbl-oss/evoting#34]
- [x] User should be able to create an account
- [x] User should be able to create election
- [x] User should be able to add candidates, time, number of voters, etc to Election. 
- [x] When a User "publishes" Election they should receive a link.
- [x] User should be able to share this link with voters #14
- [x] Voters should be verified and authenticated before they vote. (currently by password)
- [x] Voter should be able to cast vote on a candidate
- [x] Voter should not be able to vote more than once
- [x] Election can be ended and started at set time or by the Owner's request. #35 
- [x] Only "started" elections can be voted on
- [x] Secured Elections require a password to vote
- [x] Election results should be calculated after Election is finished. Results should also be saved in the db #36
- [x] The result of the elections should be available to users and can be published, but not by default. Results and notification should be sent to owner's email #39
- [x] Results should be saved and should not be allowed to be modified after voting is concluded. They should also be displayed on the Election page #37 
- [x] Election results should be shareable #38 
- [x] Allow Elections to be "embedded" #43
- [x] Prevent users that haven't signed in with passwords to vote or access election vote page #26

**Comment by LeanKhan** [comment]
Let's refer to this as a guide. @danieldutcum @AnointingMax

**Comment by LeanKhan** [comment]
Please suggest additions, removals

**Comment by danieliheonu** [comment]
I think we should add a position field to the election table and remove the position field from the candidate table

**Comment by LeanKhan** [comment]
@danieldutcum what is that field for in the Election table?

**Comment by danieliheonu** [comment]
Let's take for instance we have SGA Election, the position will be President and then we'll have candidates for that position. Do you get?

**Comment by danieliheonu** [comment]
Oh better still let's just leave it the way it is so everything will be under one election
