### ISSUE TITLE
Non-functional requirements: User Interface and Experience for version 1

### ISSUE THREAD

**Issue by LeanKhan** [bubbl-oss/evoting#58]
This is the last phase for version 1. By this point, all the functional requirements (#34) would have been implemented and we just want to make it more usable.

- [x] Add a CSS framework to speed up styling #59 
- [x] Give pages layout #60 
- [ ] Come up with a cool color scheme and sprinkle it everywhere #61 
- [ ] Add logo #62 
- [ ] Add other designs/illustrations/icons/images #63 
- [ ] Make flash messages disappear after rendering #64 
- [ ] Design homepage #65 
- [ ] Render results better using charts and tables #66 
- [x] Make the forms nicer to look at and work with #67 
- [ ] Organize code better, modules maybe #68

**Comment by LeanKhan** [comment]
Hey ma people, please peruse and comment. @AnointingMax @danieldutcum
